# docker-compose.yml file

services:

  db:
    image: metas-db:latest
    ports:
      - "15432:5432"
    healthcheck:
      test: pg_isready -h localhost -U metasfresh -d metasfresh -t 1
      interval: 5s
      timeout: 2s
      start_period: 10s
      retries: 24
    deploy:
      mode: replicated
      replicas: 1

  db-init:
    image: metas-db-init:latest
    depends_on:
      db:
        condition: service_healthy
      
  rabbitmq:
    image: rabbitmq:3.9.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=metasfresh
      - RABBITMQ_DEFAULT_PASS=metasfresh
      - RABBITMQ_DEFAULT_VHOST=/
    deploy:
      mode: replicated
      replicas: 1

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - LOG4J_FORMAT_MSG_NO_LOOKUPS=true
      - "ES_JAVA_OPTS=-Xms128M -Xmx256m"
    deploy:
      mode: replicated
      replicas: 1

# -------------------------------------------------------------------------------

  webapi:
    image: metas-api:latest
    ports:
      - "8080:8080"
      - "8789:8789"
    environment:
      - "SPRING_DATA_ELASTICSEARCH_CLIENT_REACTIVE_ENDPOINTS=search:9200"
    depends_on:
      db-init:
        condition: service_completed_successfully
    deploy:
      mode: replicated
      replicas: 1

  app:
    image: metas-app:latest
    ports:
      - "8282:8282"
      - "61616:61616"
      - "8788:8788"
    environment:
      - "SPRING_DATA_ELASTICSEARCH_CLIENT_REACTIVE_ENDPOINTS=search:9200"
    depends_on:
      db-init:
        condition: service_completed_successfully
    deploy:
      mode: replicated
      replicas: 1

  webui:
    image: metas-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webapi
      - app
    deploy:
      mode: replicated
      replicas: 1

volumes: {}
configs: {}
secrets: {}
